### ISSUE TITLE
Atualização do protótipo da home do VerSNC

### ISSUE THREAD

**Issue by moisesrlima** [culturagovbr/versnc#11]
![frame 5 2](https://user-images.githubusercontent.com/4835131/41360171-784d5c14-6f02-11e8-89de-a0eb0676e8cf.png)

**Comment by luizfpinheiro** [comment]
Atualizado, entretanto continuamos com a escolha de não utilizar o botão de 'Buscar'.

![Screenshot_2018-07-10 Versnc.png](https://images.zenhubusercontent.com/5a2e69d68a75884b908aaa52/21908f2e-6619-4442-8ebd-7d3aeb9b5501)

**Comment by luizfpinheiro** [comment]
@AnaOlivei Por favor verificar a implementação dessa issue em [Homolog](http://hmg.ver.snc.cultura.gov.br/).

**Comment by luizfpinheiro** [comment]
@AnaOlivei Certo, corrigindo. Notificarei após a atualização. 
Obs: Ainda não aplicamos a diferença entre Estados e Municípios, por enquanto os números estão de exemplo. Atualizaremos assim que aplicarmos tal diferença.

**Comment by luizfpinheiro** [comment]
@AnaOlivei O título da busca foi corrigido, por favor verificar. E a tratativa para popular com os números corretos está dependendo da issue #29.

**Comment by AnaOlivei** [comment]
@luizfpinheiro tudo certo com o título, ficou ótimo.

**Comment by luizfpinheiro** [comment]
@AnaOlivei Sobre a correção dos números acerca da quantidade de Estados e Municípios que aderiram ao SNC, foi aberta uma nova issue ( #37 ) para tratar esse detalhe.
Atualmente os dados estão preenchidos de forma fixa. Posteriormente será feita uma regra de atualização desses valores.

**Comment by AnaOlivei** [comment]
Tranquilo :-)
