### ISSUE TITLE
Diferenciar Estados e Municipios no retorno da tabela

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/versnc#14]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Não há diferença entre estado x município. 

**Qual a proposta de solução?**  
Para municípios retornar: Nome do Municipio - Estado
Para estados retornar: Nome do Estado

**Especificação da funcionalidade**  
Forma nova de visualizar os dados

**Comment by luizfpinheiro** [comment]
@AnaOlivei Por favor verificar a implementação dessa issue em [Homolog](http://hmg.ver.snc.cultura.gov.br/). 
O estados estão com o nome por extenso. O que acham dessa abordagem?

**Comment by AnaOlivei** [comment]
Está ótimo a nossa sugestão é apenas para mudar a localização como no modelo mostrado abaixo:
![image](https://user-images.githubusercontent.com/32340472/42653064-a3ef1a66-85ea-11e8-8f71-622fcc00d13e.png)

**Comment by luizfpinheiro** [comment]
@AnaOlivei Certo. Notificaremos após atualização.
