### ISSUE TITLE
Permitir visualizar somente Municípios ou Estados na Busca 

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/versnc#29]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**
Atualmente o resultado da pesquisa é composto por Municípios e Estados.

**Qual a proposta de solução?**
Uma opção para o usuário selecionar a visualização somente por Municípios ou Estados, na Busca Avançada.

**Especificação da funcionalidade**
Ao selecionar a opção e efetuar a busca, a tabela será composta somente por entes da opção selecionada.

**Comment by luizfpinheiro** [comment]
@AnaOlivei Por favor verificar implementação dessa issue em Homolog.

**Comment by AnaOlivei** [comment]
@luizfpinheiro acabei de verificar ficou ótimo!

**Comment by luizfpinheiro** [comment]
@AnaOlivei =]
Fechando issue.
