### ISSUE TITLE
Permitir pesquisar nome do Estado por extenso na Busca Avançada

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/versnc#30]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Atualmente so é possível pesquisar pela sigla do Estado (DF, BA, RJ, etc)

**Qual a proposta de solução?**  
Obter nome do Estado por meio da API

**Comment by luizfpinheiro** [comment]
Parcialmente concluído. 
Foi feita a tratativa da pesquisa de Estado por extenso na busca avançada, porém na busca simples será necessária uma outra abordagem da API.

**Comment by luizfpinheiro** [comment]
@AnaOlivei Por favor verificar a implementação dessa issue em [Homolog](http://hmg.ver.snc.cultura.gov.br/). 
Obs: Busca do estado por extenso somente na Busca Avançada. Na Simples será feita na issue #34

**Comment by AnaOlivei** [comment]
Tranquilo verificaremos na issue #34, no mais está funcionando bem.

**Comment by luizfpinheiro** [comment]
@AnaOlivei Por favor verificar a implementação dessa issue em Homolog. 
Como combinado, o desenvolvimento dessa issue dependia da #34 que também está para ser validada.

**Comment by AnaOlivei** [comment]
@luizfpinheiro verifiquei e está tudo correto.

**Comment by luizfpinheiro** [comment]
@AnaOlivei Ok. Fechando issue.
