### ISSUE TITLE
Permitir pesquisar o nome do Estado por extenso na busca Simples

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/versnc#34]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**
Atualmente so é possível pesquisar pela sigla do Estado (DF, BA, RJ, etc) ou pelo nome do município

**Qual a proposta de solução?**
Um campo de pesquisa na API que retorne Municípios e Estados como resultado.

**Comment by luizfpinheiro** [comment]
Essa issue foi aberta como fragmentação da issue #30.

**Comment by luizfpinheiro** [comment]
@AnaOlivei Olá, Ana. Por favor verificar a implementação dessa issue em Homolog.

**Comment by AnaOlivei** [comment]
@luizfpinheiro está funcionando :-)

**Comment by luizfpinheiro** [comment]
@AnaOlivei Certo. Fechando issue.
