### ISSUE TITLE
Mostrar componentes aprovados com ressalvas com check na linha expansível

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/versnc#42]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Atualmente só são mostrados com check os componentes com situação 2, isto é, concluída, é necessário que os arquivos com situação 3, isto é, aprovado com ressalvas, também sejam mostrados com o check verde.

**Comment by izacristina** [comment]
@AnaOlivei na filtragem por componentes, também é pra retornar todos que tem o componente como concluído e aprovado com ressalvas? Ou deixa somente concluído?

**Comment by AnaOlivei** [comment]
@izacristina sim é necessário que retorne os aprovados com ressalvas também.
