### ISSUE TITLE
Trocar labels "municípios" quando pesquisar estados

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/versnc#43]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Atualmente quando a pesquisa é somente de estados, no header da tabela aparece "Municípios", e na label da primeira coluna aparece "MUNICÍPIO".

**Qual a proposta de solução?**  
Trocar as labels para algo mais genérico, ou trocar para "estados" quando a pesquisa for somente de estados.

**Comment by luizfpinheiro** [comment]
Solução provisória: definir o valor dessa label de acordo com os atributos da queria de busca (estadual/municipal).
